## Predição de bons pagadores de cartão de crédito

### The Business Problem 

In [ ]:

# Default of Credit Card 30k Clients - Predictive Models
# 
# Our client is a credit card company. They have brought us a dataset that includes some demographics and 
# recent financial data (the past six months) for a sample of 30,000 of their account holders. 
# 
# This data is at the credit account level; in other words, there is one row for each account (you should always 
# clarify what the definition of a row is, in a dataset). Rows are labeled by whether in the next month after the 
# six month historical data period, an account owner has defaulted, or in other words, failed to make the minimum payment.

# Goal
# Your goal is to develop a predictive model for whether an account will default next month, given demographics 
# and historical data. Later in the book, we'll discuss the practical application of the model.

### 3. Data Exploration Steps

Verifying Basic Data Integrity

In [1]:
import pandas as pd
import numpy as np

df = pd.read_excel(
  r"\\wsl.localhost\Ubuntu\home\moiss\src_\Data Science\some_projects\inadimp\data\raw\credit_card_clients.xls",
  sheet_name=0
  )

#Total of Columns
df.columns

Index(['ID', 'LIMIT_BAL', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_1',
       'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6', 'BILL_AMT1', 'BILL_AMT2',
       'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1',
       'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6',
       'default payment next month'],
      dtype='object')

In [2]:
#Check total of lines
print("Lines:",df.shape[0])
print("Columns:",df.shape[1])

Lines: 30000
Columns: 25


In [17]:
#Store the value counts in a variable defined as id_counts and then display the 
# stored values using the .head() method, as shown:
id_counts = df['ID'].value_counts()
id_counts.head()

ID
ad23fe5c-7b09    2
1fb3e3e6-a68d    2
89f8f447-fca8    2
7c9b7473-cc2f    2
90330d02-82d9    2
Name: count, dtype: int64

In [19]:
# Display the number of grouped duplicated entries by running another value count:
id_counts.value_counts()

count
1    29374
2      313
Name: count, dtype: int64

Boolean Mask

In [28]:
# Seeting seeds = 24 to keep the same results all the time
np.random.seed(seed=24)

# Generating a serie of 100 integers between 1 and 5
random_integers = np.random.randint(low=1,high=5,size=100)
random_integers

array([3, 4, 1, 4, 2, 2, 2, 1, 4, 4, 1, 4, 4, 3, 4, 4, 4, 4, 4, 4, 2, 3,
       4, 4, 2, 4, 2, 4, 1, 1, 3, 1, 4, 2, 2, 1, 4, 3, 2, 2, 3, 3, 2, 3,
       4, 2, 3, 4, 1, 3, 4, 2, 2, 4, 1, 2, 3, 3, 2, 1, 2, 4, 2, 1, 4, 3,
       1, 2, 1, 3, 4, 2, 3, 4, 1, 3, 2, 1, 1, 3, 3, 4, 3, 2, 4, 1, 4, 4,
       4, 4, 1, 4, 3, 2, 4, 4, 3, 3, 2, 4])

In [33]:
# Suppose we wanted to know the location of all elements of random_integers equal 3:
is_equal_to_3 = random_integers == 3
is_equal_to_3

array([ True, False, False, False, False, False, False, False, False,
       False, False, False, False,  True, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False,  True, False, False,  True,  True, False,  True, False,
       False,  True, False, False,  True, False, False, False, False,
       False, False,  True,  True, False, False, False, False, False,
       False, False,  True, False, False, False,  True, False, False,
        True, False, False,  True, False, False, False,  True,  True,
       False,  True, False, False, False, False, False, False, False,
       False, False,  True, False, False, False,  True,  True, False,
       False])

In [34]:
# Sum of all found True 
is_equal_to_3.sum()

22

In [35]:
random_integers[is_equal_to_3]

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])